services:
  db:
    image: timescale/timescaledb-ha:pg15
    restart: unless-stopped
    container_name: rc_staging_db
    env_file:
      - .env.staging
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "127.0.0.1:5455:5432"
    volumes:
      - recouvrement_staging_db_data:/home/postgres/pgdata/data
    networks:
      - recouvrement_staging_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    restart: unless-stopped
    container_name: rc_staging_redis
    env_file:
      - .env.staging
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --maxmemory 256mb
      --maxmemory-policy volatile-lru
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - recouvrement_staging_redis_data:/data
    networks:
      - recouvrement_staging_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  q2:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: recouvrement_api:staging
    restart: unless-stopped
    container_name: rc_staging_q2
    env_file:
      - .env.staging
    command: python manage.py qcluster
    networks:
      - recouvrement_staging_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: recouvrement_api:staging
    restart: unless-stopped
    container_name: rc_staging_backend
    command: gunicorn config.wsgi:application -c gunicorn.conf.py
    env_file:
      - .env.staging
    ports:
      - "127.0.0.1:9101:8000"
    volumes:
      - /home/ubuntu/recouvrement_staging/staticfiles/:/home/django/config/staticfiles
    networks:
      - recouvrement_staging_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  recouvrement_staging_db_data:
  recouvrement_staging_redis_data:

networks:
  recouvrement_staging_network:
    name: recouvrement_staging_network
    driver: bridge