# Generated by Django 6.0.1 on 2026-04-14 16:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_par_paiement', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequence', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('prochaine_echeance', models.DateField(db_index=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('SOLDE', 'Soldé'), ('CONTENTIEUX', 'Contentieux')], default='ACTIF', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recouvrement_contrat',
                'permissions': [('peut_gerer_contrat', 'Peut créer et modifier des contrats'), ('peut_suspendre_contrat', 'Peut suspendre un contrat pour impayé')],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('methode', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('ESPECES', 'Espèces')], max_length=20)),
                ('date_concernee', models.DateField()),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='recouvrement.contrat')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recouvrement_paiement',
                'permissions': [('peut_valider_paiement', 'Peut valider un paiement manuel'), ('peut_annuler_paiement', 'Peut annuler une transaction erronée')],
            },
        ),
    ]
