# Generated by Django 6.0.1 on 2026-04-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={},
        ),
    ]
