# Generated by Django 6.0.1 on 2026-04-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0002_alter_contrat_options_alter_paiement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'permissions': [('can_validate_payment', 'Peut valider un paiement manuel (Espèces)'), ('can_cancel_payment', 'Peut annuler une transaction erronée')]},
        ),
    ]
