# Generated by Django 6.0.1 on 2026-04-15 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0003_alter_paiement_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrat',
            options={'permissions': [('view_all_contrats', 'Peut voir tous les contrats de son entreprise')]},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'permissions': [('can_validate_payment', 'Peut valider un paiement manuel (Espèces)'), ('can_cancel_payment', 'Peut annuler une transaction erronée'), ('view_all_paiements', 'Peut voir tous les paiements de son entreprise')]},
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='contrat',
            name='chauffeur',
            field=models.ForeignKey(default=1, help_text='Le chauffeur (DRIVER) qui loue le véhicule et doit payer.', on_delete=django.db.models.deletion.PROTECT, related_name='contrats_a_payer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, help_text="L'agent (PARTNER_ADMIN) qui a saisi ce contrat dans le système.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_enregistres', to=settings.AUTH_USER_MODEL),
        ),
    ]
