# Generated by Django 6.0.1 on 2026-04-20 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0004_alter_contrat_options_alter_paiement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='date_concernee',
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_echeance', models.DateField(db_index=True)),
                ('montant_attendu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('NON_PAYE', 'Non payé'), ('PARTIEL', 'Partiellement payé'), ('PAYE', 'Payé')], default='NON_PAYE', max_length=20)),
                ('contrat', models.ForeignKey(help_text='Le contrat auquel cette échéance journalière est rattachée.', on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='recouvrement.contrat')),
            ],
            options={
                'db_table': 'recouvrement_lease',
                'permissions': [('view_all_leases', "Peut voir toutes les échéances de l'entreprise")],
                'unique_together': {('contrat', 'date_echeance')},
            },
        ),
    ]
