# Generated by Django 6.0.1 on 2026-04-20 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0005_remove_paiement_date_concernee_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='recouvrement.lease'),
        ),
    ]
