# Generated by Django 6.0.1 on 2026-04-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0006_paiement_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='webhook_payload',
            field=models.JSONField(blank=True, help_text='Stocke la copie exacte du dernier webhook reçu du fournisseur.', null=True),
        ),
    ]
