# Generated by Django 6.0.1 on 2026-04-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0007_paiement_webhook_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
