# Generated by Django 6.0.1 on 2026-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0008_contrat_immatriculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='frequence',
            field=models.CharField(choices=[('JOURNALIER', 'Journalier'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel (Par mois)')], default='JOURNALIER', max_length=50),
        ),
    ]
