# Generated by Django 6.0.1 on 2026-04-22 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0009_alter_contrat_frequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='date_paiement',
            new_name='date_paiement_local',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='statut',
            new_name='statut_local',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='webhook_payload',
        ),
        migrations.AddField(
            model_name='paiement',
            name='est_annule',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SessionPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, help_text='ID transaction fournisseur', max_length=255, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('webhook_payload', models.JSONField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_initiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recouvrement_session_paiement',
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_paiement', to='recouvrement.sessionpaiement'),
        ),
    ]
