# Generated by Django 6.0.1 on 2026-04-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0010_rename_date_paiement_paiement_date_paiement_local_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='date_paiement_local',
            new_name='date_paiement',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='statut_local',
            new_name='statut',
        ),
    ]
