# Generated by Django 6.0.1 on 2026-05-06 11:40
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0011_rename_date_paiement_local_paiement_date_paiement_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
