# Generated by Django 6.0.1 on 2026-05-06 11:51

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0012_auto_20260506_1240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('est_principal', models.BooleanField(default=False, help_text="Cochez si c'est un contrat principal (ex: Véhicule). Laissez décoché pour des accessoires.")),
            ],
            options={
                'db_table': 'recouvrement_type_contrat',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lease',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contrat',
            name='nom_complet_search',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Si ce contrat est un accessoire, sélectionnez le contrat principal ici.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sous_contrats', to='recouvrement.contrat'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Numéro de châssis (VIN)'),
        ),
        migrations.AddField(
            model_name='lease',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='nom_complet_search',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='nom_complet_search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, help_text="L'agent (PARTNER_ADMIN) qui a saisi ce contrat dans le système.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats_enregistres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['-created_at'], name='idx_lease_created_at'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom_complet_search'], name='idx_lease_search_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['compte_id', '-created_at'], name='idx_lease_tenant_date'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['-created_at'], name='idx_paie_created_at'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['compte_id', '-created_at'], name='idx_paie_tenant_date'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom_complet_search'], name='idx_paie_search_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='sessionpaiement',
            index=models.Index(fields=['compte_id', '-created_at'], name='idx_spaie_tenant_date'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(fields=('contrat', 'date_echeance'), name='unique_lease_par_contrat_et_date'),
        ),
        migrations.AddConstraint(
            model_name='typecontrat',
            constraint=models.UniqueConstraint(fields=('libelle', 'code', 'compte_id'), name='unique_type_contrat'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='type_contrat',
            field=models.ForeignKey(help_text='La catégorie de ce contrat (Véhicule, Téléphone, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='recouvrement.typecontrat'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['-created_at'], name='idx_contrat_created_at'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom_complet_search'], name='idx_cntr_search_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['immatriculation'], name='idx_contrat_immat'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['vin'], name='idx_contrat_vin'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['compte_id', '-created_at'], name='idx_contrat_tenant_date'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True), models.Q(('statut__in', ['SOLDE', 'ANNULE']), _negated=True)), fields=('chauffeur',), name='uniq_contrat_parent_actif_par_chauffeur'),
        ),
    ]
