# Generated by Django 6.0.1 on 2026-05-06 14:21

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0013_typecontrat_alter_lease_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='reference',
            field=models.CharField(blank=True, help_text='Généré automatiquement (ex: RYLVEH202600012)', max_length=50, unique=True, verbose_name='Référence du contrat'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='nom_complet_search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=django.contrib.postgres.indexes.GinIndex(fields=['reference'], name='idx_cntr_ref_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
