# Generated by Django 6.0.1 on 2026-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0014_contrat_reference_alter_contrat_nom_complet_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Détails techniques ou notes (ex: Marque Samsung A14, 4Go RAM, IMEI...)', null=True, verbose_name='Commentaires et Spécificités'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='prochaine_echeance',
            field=models.DateField(),
        ),
    ]
