# Generated by Django 6.0.1 on 2026-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0015_contrat_commentaire_alter_contrat_date_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='contrat',
            name='specificites',
            field=models.JSONField(blank=True, default=dict, help_text="Attributs variables (ex: {'marque': 'Samsung', 'imei': '123...'})", null=True, verbose_name='Spécificités Techniques (JSON)'),
        ),
    ]
