# Generated by Django 6.0.1 on 2026-05-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0016_remove_contrat_commentaire_contrat_specificites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='specificites',
            field=models.JSONField(blank=True, default=None, help_text="Attributs variables (ex: {'marque': 'Samsung', 'imei': '123...'})", null=True, verbose_name='Spécificités Techniques (JSON)'),
        ),
    ]
