# Generated by Django 6.0.1 on 2026-05-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0017_alter_contrat_specificites'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='typecontrat',
            name='unique_type_contrat',
        ),
        migrations.AlterField(
            model_name='typecontrat',
            name='code',
            field=models.SlugField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='typecontrat',
            constraint=models.UniqueConstraint(fields=('code', 'compte_id'), name='unique_type_contrat_code_par_compte'),
        ),
    ]
