# Generated by Django 6.0.1 on 2026-05-08 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0018_remove_typecontrat_unique_type_contrat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='utilisateur',
            new_name='enregistre_par',
        ),
    ]
