# Generated by Django 6.0.1 on 2026-05-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0019_rename_utilisateur_paiement_enregistre_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jours_repos', models.JSONField(default=list, help_text='Liste des jours ignorés pour les échéances (0=Lundi, ..., 6=Dimanche). Ex: [6] pour sauter le dimanche.')),
            ],
            options={
                'db_table': 'recouvrement_parametre',
                'constraints': [models.UniqueConstraint(fields=('compte_id',), name='unique_param_par_compte')],
            },
        ),
    ]
