# Generated by Django 6.0.1 on 2026-06-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0020_parametre'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
