# Generated by Django 6.0.1 on 2026-06-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0021_contrat_montant_paye'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contrat',
            table='rc_contrat',
        ),
        migrations.AlterModelTable(
            name='lease',
            table='rc_lease',
        ),
        migrations.AlterModelTable(
            name='paiement',
            table='rc_paiement',
        ),
        migrations.AlterModelTable(
            name='parametre',
            table='rc_parametre',
        ),
        migrations.AlterModelTable(
            name='sessionpaiement',
            table='rc_session_paiement',
        ),
        migrations.AlterModelTable(
            name='typecontrat',
            table='rc_type_contrat',
        ),
    ]
