# Generated by Django 6.0.1 on 2026-06-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0022_alter_contrat_table_alter_lease_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionpaiement',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='sessionpaiement',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
