# Generated by Django 6.0.1 on 2026-06-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0023_remove_sessionpaiement_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recouvrement.sessionpaiement',),
        ),
    ]
