# Generated by Django 6.0.1 on 2026-06-18 15:07

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0024_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglePenalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(help_text='Ex: Tous les jours à 15h, Hebdomadaire le lundi...', max_length=100, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la pénalité (FCFA)')),
                ('occurrences', models.IntegerField(default=-1, help_text='Nombre maximum de pénalités. Mettre -1 pour infini, 0 pour désactiver.')),
                ('frequence', models.CharField(choices=[('O', 'Une seule fois'), ('H', 'Toutes les heures'), ('D', 'Tous les jours'), ('W', 'Toutes les semaines'), ('M', 'Tous les mois'), ('C', 'Expression Cron (Avancé)')], default='D', max_length=1, verbose_name="Fréquence d'exécution")),
                ('cron_expression', models.CharField(blank=True, help_text="Ex: '0 10,14,18 * * *' (Requis si Fréquence = Cron).", max_length=100, null=True)),
                ('debut', models.DateTimeField(help_text='Détermine le moment exact (Date + Heure) où la tâche commencera son cycle.', verbose_name='Date et heure de première exécution')),
            ],
            options={
                'verbose_name': 'Règle de Pénalité',
                'verbose_name_plural': 'Règles de Pénalité',
                'db_table': 'rc_regle_penalite',
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='regle_penalite',
            field=models.ForeignKey(blank=True, help_text='Associer une règle pour activer la planification automatique des pénalités de retard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='recouvrement.reglepenalite', verbose_name='Règle de pénalité appliquée'),
        ),
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_complet', models.CharField(help_text="Nom figé au moment de l'application de la pénalité pour l'audit.", max_length=255, verbose_name='Nom complet du chauffeur')),
                ('nom_complet_search', models.CharField(blank=True, max_length=255, verbose_name='Nom complet (Recherche optimisée)')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la pénalité (FCFA)')),
                ('date_application', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de sanction')),
                ('motif', models.CharField(help_text='Ex: Première pénalité de retard, 2ème occurrence...', max_length=255, verbose_name='Motif / Justification')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalites', to='recouvrement.lease', verbose_name='Échéance associée')),
            ],
            options={
                'verbose_name': 'Pénalité de retard',
                'verbose_name_plural': 'Pénalités de retard',
                'db_table': 'rc_penalite',
                'ordering': ['-date_application'],
                'indexes': [models.Index(fields=['-date_application'], name='idx_penalite_date_desc'), models.Index(fields=['lease', '-date_application'], name='idx_penalite_lease_date'), django.contrib.postgres.indexes.GinIndex(fields=['nom_complet_search'], name='idx_penal_search_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
