# Generated by Django 6.0.1 on 2026-06-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0025_reglepenalite_contrat_regle_penalite_penalite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalite',
            options={'ordering': ['-date_application'], 'permissions': [('view_all_penalites', "Peut voir toutes les pénalités de l'entreprise")], 'verbose_name': 'Pénalité de retard', 'verbose_name_plural': 'Pénalités de retard'},
        ),
    ]
