# Generated by Django 6.0.1 on 2026-06-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0026_alter_penalite_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='reference',
        ),
    ]
