# Generated by Django 6.0.1 on 2026-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0027_remove_paiement_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionpaiement',
            options={'permissions': [('view_all_sessionpaiements', 'Peut voir toutes les sessions de paiement du compte')]},
        ),
        migrations.AddIndex(
            model_name='reglepenalite',
            index=models.Index(fields=['frequence'], name='idx_regle_frequence'),
        ),
    ]
