# Generated by Django 6.0.1 on 2026-06-25 15:37

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0028_alter_sessionpaiement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalite',
            name='statut',
            field=models.CharField(choices=[('NON_PAYE', 'Non payé'), ('PARTIEL', 'Partiellement payé'), ('PAYE', 'Payé')], default='NON_PAYE', max_length=20),
        ),
        migrations.AddField(
            model_name='reglepenalite',
            name='nom_search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='reglepenalite',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom_search'], name='idx_nom_search_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
