# Generated by Django 6.0.1 on 2026-06-25 16:00

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0029_penalite_statut_reglepenalite_nom_search_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sessionpaiement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['reference'], name='idx_spaie_ref_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='sessionpaiement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['telephone'], name='idx_spaie_tel_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
