# Generated by Django 6.0.1 on 2026-07-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0030_sessionpaiement_idx_spaie_ref_trgm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='statut',
            field=models.CharField(choices=[('NON_PAYE', 'Non payé'), ('PARTIEL', 'Partiellement payé'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé (Absence/Panne)')], default='NON_PAYE', max_length=20),
        ),
    ]
