# Generated by Django 6.0.1 on 2026-07-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0031_alter_lease_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
