# Generated by Django 6.0.1 on 2026-07-30 10:48

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0032_alter_contrat_montant_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='prochaine_echeance',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='RegleGenerationLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(help_text="Ex: 'Classique 24h', 'Demi-journée 12h/22h', 'Hebdomadaire'...", max_length=100, unique=True)),
                ('nom_search', models.CharField(blank=True, max_length=255, null=True)),
                ('frequence', models.CharField(choices=[('O', 'Une seule fois'), ('H', 'Toutes les heures'), ('D', 'Tous les jours'), ('W', 'Toutes les semaines'), ('M', 'Tous les mois'), ('C', 'Expression Cron (Avancé)')], default='D', max_length=1, verbose_name="Fréquence d'exécution")),
                ('cron_expression', models.CharField(blank=True, help_text="Ex: '0 12,22 * * *' (Requis si Fréquence = Cron).", max_length=100, null=True)),
                ('debut', models.DateTimeField(help_text='Détermine le moment exact (Date + Heure) où le cycle commencera.', verbose_name='Date et heure de première exécution')),
                ('actif', models.BooleanField(default=True, help_text='Si désactivé, AUCUN contrat lié à cette règle ne sera facturé.', verbose_name='Règle active')),
            ],
            options={
                'verbose_name': 'Règle de Facturation',
                'verbose_name_plural': 'Règles de Facturation',
                'db_table': 'rc_regle_facturation',
                'indexes': [models.Index(fields=['frequence'], name='idx_regle_lease_freq'), django.contrib.postgres.indexes.GinIndex(fields=['nom_search'], name='idx_lease_nom_search_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='regle_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='recouvrement.reglegenerationlease', verbose_name='Règle de génération'),
        ),
    ]
