# Generated by Django 6.0.1 on 2026-07-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0033_alter_contrat_prochaine_echeance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reglegenerationlease',
            options={'verbose_name': 'Règle de génération de leases', 'verbose_name_plural': 'Règles de génération de leases'},
        ),
        migrations.AlterModelTable(
            name='reglegenerationlease',
            table='rc_regle_generation_lease',
        ),
    ]
