# Generated by Django 6.0.1 on 2026-07-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0034_alter_reglegenerationlease_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='date_echeance',
            field=models.DateTimeField(db_index=True),
        ),
    ]
