# Generated by Django 6.0.1 on 2026-08-31 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0041_config_paiement_facultative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('code', models.SlugField()),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'db_table': 'rc_agence',
                'indexes': [models.Index(fields=['compte_id', 'actif'], name='idx_agence_compte_actif')],
                'constraints': [models.UniqueConstraint(fields=('compte_id', 'code'), name='unique_agence_code_par_compte')],
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='agence',
            field=models.ForeignKey(blank=True, help_text="Agence propriétaire du contrat. Ce champ reste temporairement facultatif pendant l'affectation des contrats existants.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='recouvrement.agence'),
        ),
    ]
