# Generated by Django 6.0.1 on 2026-08-31 16:18

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0042_agence_contrat_agence'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='agence',
            field=models.ForeignKey(blank=True, help_text="Agence propriétaire de cette donnée. Le champ reste temporairement facultatif pendant la reprise de l'historique.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='recouvrement.agence'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='agence',
            field=models.ForeignKey(blank=True, help_text="Agence propriétaire de cette donnée. Le champ reste temporairement facultatif pendant la reprise de l'historique.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='recouvrement.agence'),
        ),
        migrations.AddField(
            model_name='penalite',
            name='agence',
            field=models.ForeignKey(blank=True, help_text="Agence propriétaire de cette donnée. Le champ reste temporairement facultatif pendant la reprise de l'historique.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='recouvrement.agence'),
        ),
        migrations.AddField(
            model_name='sessionpaiement',
            name='agence',
            field=models.ForeignKey(blank=True, help_text="Agence propriétaire de cette donnée. Le champ reste temporairement facultatif pendant la reprise de l'historique.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='recouvrement.agence'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='agence',
            field=models.ForeignKey(blank=True, help_text="Agence propriétaire de cette donnée. Le champ reste temporairement facultatif pendant la reprise de l'historique.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='recouvrement.agence'),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['nom'], name='idx_agence_nom'),
        ),
    ]
