# Generated by Django 6.0.1 on 2026-08-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0043_lease_agence_paiement_agence_penalite_agence_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agence',
            name='idx_agence_nom',
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['nom'], name='idx_agence_nom'),
        ),
    ]
