# Generated by Django 6.0.1 on 2026-09-01 16:00

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0044_remove_agence_idx_agence_nom_agence_idx_agence_nom'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agence',
            name='idx_agence_nom',
        ),
        migrations.AddField(
            model_name='agence',
            name='nom_search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom_search'], name='idx_agence_nom_search_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
