# Generated by Django 6.0.1 on 2026-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0045_remove_agence_idx_agence_nom_agence_nom_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglegenerationlease',
            name='defaut',
            field=models.BooleanField(default=False, help_text='Si coché, cette règle sera automatiquement appliquée aux nouveaux contrats.', verbose_name='Règle par défaut'),
        ),
    ]
