# Generated by Django 6.0.1 on 2026-09-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0046_reglegenerationlease_defaut'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reglegenerationlease',
            constraint=models.UniqueConstraint(condition=models.Q(('defaut', True)), fields=('compte_id',), name='unique_regle_generation_defaut_par_compte'),
        ),
    ]
