# Generated by Django 6.0.1 on 2026-09-03 14:31

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0048_align_subcontract_payment_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='zone',
            field=models.CharField(blank=True, help_text="Zone géographique utilisée pour regrouper plusieurs agences d'une même ville ou région.", max_length=100, verbose_name='Zone / Ville'),
        ),
        migrations.AddField(
            model_name='agence',
            name='zone_search',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=django.contrib.postgres.indexes.GinIndex(fields=['zone_search'], name='idx_agence_zone_search_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['code'], name='idx_agence_code'),
        ),
    ]
