# Generated by Django 6.0.1 on 2026-09-08 12:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_unique_config_paiement_defaut_par_compte'),
        ('recouvrement', '0050_proprietaires_filgrace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreuvePaiementUSSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operateur', models.CharField(choices=[('ORANGE', 'Orange Money'), ('MTN', 'MTN Mobile Money')], max_length=10)),
                ('reference_operateur', models.CharField(max_length=100)),
                ('texte_brut', models.TextField()),
                ('montant_transfere', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frais_operateur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('nouveau_solde', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nom_expediteur', models.CharField(blank=True, max_length=255)),
                ('numero_expediteur', models.CharField(max_length=20)),
                ('nom_destinataire', models.CharField(blank=True, max_length=255)),
                ('numero_destinataire', models.CharField(max_length=20)),
                ('date_transaction', models.DateTimeField(blank=True, null=True)),
                ('capture_appareil_le', models.DateTimeField()),
                ('payload_capture', models.JSONField(default=dict)),
                ('statut', models.CharField(choices=[('EN_VERIFICATION', 'En vérification'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_VERIFICATION', max_length=20)),
                ('verifie_le', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Preuve de paiement USSD',
                'verbose_name_plural': 'Preuves de paiement USSD',
                'db_table': 'rc_preuve_paiement_ussd',
                'permissions': [('can_validate_ussd_payment', 'Peut valider ou rejeter une preuve de paiement USSD')],
            },
        ),
        migrations.AddField(
            model_name='sessionpaiement',
            name='canal',
            field=models.CharField(choices=[('PASSERELLE', 'Passerelle Mobile Money'), ('USSD_ASSISTE', 'Paiement USSD assisté')], default='PASSERELLE', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionpaiement',
            name='compte_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_paiement', to='recouvrement.comptereceptionproprietaire'),
        ),
        migrations.AddField(
            model_name='sessionpaiement',
            name='nom_destinataire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sessionpaiement',
            name='numero_destinataire',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sessionpaiement',
            name='operateur',
            field=models.CharField(blank=True, choices=[('ORANGE', 'Orange Money'), ('MTN', 'MTN Mobile Money')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sessionpaiement',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_paiement', to='recouvrement.proprietaire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('USSD_ASSISTE', 'USSD assisté'), ('ESPECES', 'Espèces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionpaiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_VERIFICATION', 'En vérification'), ('VALIDE', 'Validé'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sessionpaiement',
            index=models.Index(fields=['compte_id', 'canal', 'statut'], name='idx_spaie_cpte_canal_stat'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(condition=models.Q(('methode', 'USSD_ASSISTE'), ('statut', 'EN_ATTENTE'), ('est_annule', False)), fields=('lease',), name='uniq_paie_ussd_attente_lease'),
        ),
        migrations.AddField(
            model_name='preuvepaiementussd',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preuve_ussd', to='recouvrement.sessionpaiement'),
        ),
        migrations.AddField(
            model_name='preuvepaiementussd',
            name='verifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preuves_ussd_verifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='preuvepaiementussd',
            index=models.Index(fields=['compte_id', 'statut', '-created_at'], name='idx_preuve_cpte_stat_date'),
        ),
        migrations.AddIndex(
            model_name='preuvepaiementussd',
            index=models.Index(fields=['numero_destinataire'], name='idx_preuve_dest_numero'),
        ),
        migrations.AddConstraint(
            model_name='preuvepaiementussd',
            constraint=models.UniqueConstraint(fields=('compte_id', 'operateur', 'reference_operateur'), name='uniq_preuve_ref_oper_compte'),
        ),
    ]
