# Generated by Django 6.0.1 on 2026-09-10 02:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0051_paiement_ussd_assiste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('PANNE', 'Panne / réparation'), ('VIDANGE', 'Vidange'), ('ENTRETIEN', 'Entretien courant'), ('ASSURANCE', 'Assurance'), ('AMENDE', 'Amende'), ('PIECE_DETACHEE', 'Pièce détachée'), ('CARBURANT', 'Carburant'), ('AUTRE', 'Autre')], max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_depense', models.DateField(help_text="Date à laquelle la dépense a eu lieu (distincte de la date d'enregistrement).", verbose_name='Date de la dépense')),
                ('fournisseur', models.CharField(blank=True, max_length=255, verbose_name='Fournisseur / prestataire')),
                ('kilometrage', models.PositiveIntegerField(blank=True, help_text='Relevé au compteur au moment de la dépense, si pertinent.', null=True, verbose_name='Kilométrage au compteur')),
                ('agence', models.ForeignKey(blank=True, help_text="Agence propriétaire de cette donnée. Le champ reste temporairement facultatif pendant la reprise de l'historique.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='recouvrement.agence')),
                ('contrat', models.ForeignKey(help_text='Contrat concerné par cette dépense.', on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='recouvrement.contrat')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'db_table': 'rc_depense',
                'indexes': [models.Index(fields=['compte_id', '-date_depense'], name='idx_depense_tenant_date'), models.Index(fields=['contrat'], name='idx_depense_contrat')],
            },
        ),
    ]
