# Generated by Django 6.0.1 on 2026-09-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0052_depense'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paiement',
            name='uniq_paie_ussd_attente_lease',
        ),
    ]
