# Generated by Django 6.0.1 on 2026-09-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recouvrement', '0053_remove_paiement_uniq_paie_ussd_attente_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='kilometrage',
        ),
    ]
