# Generated by Django 6.0.1 on 2026-04-14 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keycloak_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Keycloak ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('nom_complet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Complet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès Admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super Admin')),
            ],
            options={
                'db_table': 'recouvrement_customuser',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('niveau', models.PositiveSmallIntegerField(default=0)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles_recouvrement', to='auth.permission')),
            ],
            options={
                'db_table': 'recouvrement_role',
            },
        ),
        migrations.CreateModel(
            name='CustomUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('assigne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assignes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignations_utilisateurs', to='accounts.role')),
            ],
            options={
                'db_table': 'recouvrement_customuser_role',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.CustomUserRole', through_fields=('user', 'role'), to='accounts.role'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['slug'], name='idx_rec_role_slug'),
        ),
        migrations.AddIndex(
            model_name='customuserrole',
            index=models.Index(fields=['compte_id', 'user'], name='recouvremen_compte__75f2fb_idx'),
        ),
        migrations.AddIndex(
            model_name='customuserrole',
            index=models.Index(fields=['compte_id', 'role'], name='recouvremen_compte__c01443_idx'),
        ),
        migrations.AddIndex(
            model_name='customuserrole',
            index=models.Index(fields=['user', 'role'], name='recouvremen_user_id_53ec16_idx'),
        ),
        migrations.AddIndex(
            model_name='customuserrole',
            index=models.Index(fields=['compte_id', 'actif'], name='recouvremen_compte__c38446_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuserrole',
            constraint=models.UniqueConstraint(fields=('compte_id', 'user', 'role'), name='uniq_role_par_user_par_compte_rec'),
        ),
        migrations.AddConstraint(
            model_name='customuserrole',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('user',), name='uniq_role_principal_par_user_rec'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['compte_id', 'is_active'], name='recouvremen_compte__b9c2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['keycloak_id'], name='idx_rec_user_kc_id'),
        ),
    ]
