# Generated by Django 6.0.1 on 2026-04-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='account_cus_compte__2fa600_idx',
            old_name='recouvremen_compte__b9c2e1_idx',
        ),
        migrations.RenameIndex(
            model_name='customuserrole',
            new_name='account_cus_compte__e05ecd_idx',
            old_name='recouvremen_compte__75f2fb_idx',
        ),
        migrations.RenameIndex(
            model_name='customuserrole',
            new_name='account_cus_compte__3aa5d1_idx',
            old_name='recouvremen_compte__c01443_idx',
        ),
        migrations.RenameIndex(
            model_name='customuserrole',
            new_name='account_cus_user_id_0e7072_idx',
            old_name='recouvremen_user_id_53ec16_idx',
        ),
        migrations.RenameIndex(
            model_name='customuserrole',
            new_name='account_cus_compte__1d6dd2_idx',
            old_name='recouvremen_compte__c38446_idx',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='account_customuser',
        ),
        migrations.AlterModelTable(
            name='customuserrole',
            table='account_customuser_role',
        ),
        migrations.AlterModelTable(
            name='role',
            table='account_role',
        ),
    ]
