# Generated by Django 6.0.1 on 2026-04-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_contrat_utilisateur_remove_paiement_contrat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_all_users', 'Peut voir tous les utilisateurs de son entreprise (Tenant)')]},
        ),
    ]
