# Generated by Django 6.0.1 on 2026-05-06 11:51

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuserrole',
            name='account_cus_compte__e05ecd_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuserrole',
            name='account_cus_compte__3aa5d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuserrole',
            name='account_cus_user_id_0e7072_idx',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nom_complet_search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='keycloak_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Keycloak ID'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom_complet_search'], name='idx_user_search_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
