# Generated by Django 6.0.1 on 2026-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuserrole_account_cus_compte__e05ecd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nom_complet',
            field=models.CharField(default='Christian', max_length=255, verbose_name='Nom Complet'),
            preserve_default=False,
        ),
    ]
