# Generated by Django 6.0.1 on 2026-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_nom_complet'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('email__isnull', True), _negated=True), models.Q(('email__exact', ''), _negated=True)), fields=('email',), name='unique_email_if_not_null'),
        ),
    ]
