# Generated by Django 6.0.1 on 2026-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_unique_email_if_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(help_text='Clé API fournie par PayGate (ex: Api-Key...)', max_length=255, verbose_name="Clé d'API Passerelle")),
                ('base_url', models.URLField(help_text='Ex de format: https://api.paygate.cm', verbose_name="URL de base de l'API")),
                ('success_url', models.URLField(help_text='URL vers laquelle le chauffeur est redirigé après son paiement réussi.', verbose_name='URL de redirection en cas de succès')),
                ('webhook_url', models.URLField(blank=True, help_text="L'URL de notre API que PayGate doit appeler (utile pour l'affichage ou la synchro).", null=True, verbose_name='URL du Webhook local')),
                ('webhook_secret', models.CharField(help_text='Clé secrète partagée pour vérifier la signature HMAC (X-Signature) des notifications reçues.', max_length=255, verbose_name='Secret de validation du Webhook')),
            ],
            options={
                'db_table': 'account_config_paiement',
                'constraints': [models.UniqueConstraint(fields=('compte_id',), name='unique_config_paiement_par_compte')],
            },
        ),
    ]
