# Generated by Django 6.0.1 on 2026-06-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_configpaiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configpaiement',
            name='webhook_url',
        ),
    ]
