# Generated by Django 6.0.1 on 2026-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_configpaiement_par_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='configpaiement',
            name='defaut',
            field=models.BooleanField(default=False, help_text='Si coché, cette configuration sera automatiquement assignée aux nouveaux contrats.', verbose_name='Configuration par défaut'),
        ),
    ]
