# Generated by Django 6.0.1 on 2026-09-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_configpaiement_defaut'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='configpaiement',
            constraint=models.UniqueConstraint(condition=models.Q(('defaut', True)), fields=('compte_id',), name='unique_config_paiement_defaut_par_compte'),
        ),
    ]
