# Generated by Django 6.0.1 on 2026-05-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('montant_attendu', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_collecte', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_echec', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_attendus', models.IntegerField(default=0)),
                ('ayant_verse', models.IntegerField(default=0)),
                ('n_ayant_pas_verse', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'statistique_journaliere',
                'indexes': [models.Index(fields=['compte_id', '-date'], name='statistique_compte__1de226_idx')],
                'unique_together': {('compte_id', 'date')},
            },
        ),
    ]
