# Generated by Django 6.0.1 on 2026-06-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistiques', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statistiquejournaliere',
            new_name='re_stat_jou_compte__51fcb4_idx',
            old_name='statistique_compte__1de226_idx',
        ),
        migrations.AlterModelTable(
            name='statistiquejournaliere',
            table='re_stat_journaliere',
        ),
    ]
