# Generated by Django 6.0.1 on 2026-06-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistiques', '0002_rename_statistique_compte__1de226_idx_re_stat_jou_compte__51fcb4_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statistiquejournaliere',
            new_name='rc_stat_jou_compte__27b560_idx',
            old_name='re_stat_jou_compte__51fcb4_idx',
        ),
        migrations.AlterModelTable(
            name='statistiquejournaliere',
            table='rc_stat_journaliere',
        ),
    ]
