# Generated by Django 6.0.1 on 2026-06-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistiques', '0003_rename_re_stat_jou_compte__51fcb4_idx_rc_stat_jou_compte__27b560_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statistiquejournaliere',
            new_name='idx_stat_tenant_date',
            old_name='rc_stat_jou_compte__27b560_idx',
        ),
        migrations.AlterUniqueTogether(
            name='statistiquejournaliere',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='statistiquejournaliere',
            constraint=models.UniqueConstraint(fields=('compte_id', 'date'), name='unique_stat_par_compte_et_date'),
        ),
    ]
